version: '3'
services:  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
    depends_on:
      - web
 
